### ISSUE TITLE
macos failed to copy theme to fleet 

### ISSUE THREAD

**Issue by jumuning** [kkrypt0nn/jetbrains-fleet#1]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/26852131/229328073-b9b3a875-eeb9-4f5f-9004-271b2cc000b2.png">
Putting theme files into fleet has no effect 
<img width="733" alt="image" src="https://user-images.githubusercontent.com/26852131/229328131-761c8e8f-b437-418f-bbbb-b3b1033f2c66.png">

**Comment by kkrypt0nn** [comment]
Not sure how you came with the weird idea to view the package content of the Fleet application itself and add a folder in there but that's not what's written in the README file.

> Go to `~/.fleet`

`~` means the home directory, so `/Users/<username/` so you end up having to paste the folder in `/Users/<username>/.fleet` just like the following:
<img width="1032" alt="Screenshot 2023-04-02 at 14 24 49" src="https://user-images.githubusercontent.com/43011723/229355299-1c6e211b-a79e-4062-9117-728bc2b876da.png">
